// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcm8jFwUM6WFrM3nCsdHR1VPkZpkO0uwA',
    appId: '1:354522160966:web:d0b288b584269614f78f47',
    messagingSenderId: '354522160966',
    projectId: 'roadfixqc-admin',
    authDomain: 'roadfixqc-admin.firebaseapp.com',
    storageBucket: 'roadfixqc-admin.firebasestorage.app',
    measurementId: 'G-ZFYSLKS4DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK2Mm0Gr2m4OwTL2rwN8yckWbTIKVbqQ8',
    appId: '1:354522160966:android:b0bf682e679f7942f78f47',
    messagingSenderId: '354522160966',
    projectId: 'roadfixqc-admin',
    storageBucket: 'roadfixqc-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARV6MS_9S0HLXw5seqCqimR9CbfuSPu3c',
    appId: '1:354522160966:ios:0804d9c6543bdc5ff78f47',
    messagingSenderId: '354522160966',
    projectId: 'roadfixqc-admin',
    storageBucket: 'roadfixqc-admin.firebasestorage.app',
    iosClientId: '354522160966-lk1c163aqe18u9c46mt9bgcj7jqdnj7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARV6MS_9S0HLXw5seqCqimR9CbfuSPu3c',
    appId: '1:354522160966:ios:0804d9c6543bdc5ff78f47',
    messagingSenderId: '354522160966',
    projectId: 'roadfixqc-admin',
    storageBucket: 'roadfixqc-admin.firebasestorage.app',
    iosClientId: '354522160966-lk1c163aqe18u9c46mt9bgcj7jqdnj7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcm8jFwUM6WFrM3nCsdHR1VPkZpkO0uwA',
    appId: '1:354522160966:web:290f82486fe1e66af78f47',
    messagingSenderId: '354522160966',
    projectId: 'roadfixqc-admin',
    authDomain: 'roadfixqc-admin.firebaseapp.com',
    storageBucket: 'roadfixqc-admin.firebasestorage.app',
    measurementId: 'G-98VQ19WHQ9',
  );
}
